#!/bin/bash

full_path="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
export ADPSSP_ROOT=`dirname "$full_path" | sed 's/\/bin$//'`

cctbx.python ${ADPSSP_ROOT}/adpssp.py $@

#cat > coot.sh << eof
#module load ccp4
#coot --python -c 'make_and_draw_map("sad.mtz", "F", "PHI", "/HKL_base/HKL_base/FOM", 1, 0)' --no-guano
#eof

